language: php

php:
  - 5.6
  - 7.2
  - nightly

cache:
  directories:
    - $HOME/.composer

before_script:
  - phpenv config-rm xdebug.ini || true
  - if [ "$MIN_STABILITY" != "" ]; then composer config minimum-stability $MIN_STABILITY; fi
  - composer require phpunit/phpunit:${PHPUNIT}

script:
  - ./vendor/bin/phpunit
